#!/bin/bash

maxexp=50
exp=1

fixedparam=" terminationmaxevaluation=100000 statisticsample=100000  terminationhitvalue=true terminationhitvaluesleep=false  minimization=false crossover=geneura.org.operators.binary.UniformCrossover terminationnotimproved=false churn=false  chromosomesize=24 entropy=false evaluation=geneura.samples.traps.Trap3 algorithm=GGA"







while [ $exp -le $maxexp ]; do



echo GGA $exp

echo gR 0
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.0 populationsize=3120 >> ggagR0

echo gR 0.1
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.0056 populationsize=2808 >> ggagR01
 
echo gR 0.3
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.017 populationsize=2184 >> ggagR03

echo gR 0.5
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.028 populationsize=1560 >> ggagR05

echo gR 0.7
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.039 populationsize=936 >> ggagR07

echo gR 0.9
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.05 populationsize=312 >> ggagR09

echo gR 0.99
java -Xmx1024M -cp "$CLASSPATH:../lib/*" geneura.org.EvoGen $fixedparam mutationprobability=0.055 populationsize=32 >> ggagR099




	exp=$[ $exp + 1 ]
done

